name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Create release package
        run: |
          mkdir -p dist
          tar -czf dist/ept-mx-adm-${{ github.ref_name }}.tar.gz \
            --exclude='.git*' \
            --exclude='tests' \
            --exclude='*.pyc' \
            --exclude='__pycache__' \
            --exclude='venv' \
            --exclude='dist' \
            .
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: EPT-MX-ADM ${{ github.ref_name }}
          body: |
            ## EPT-MX-ADM Release ${{ github.ref_name }}
            
            Modern administration panel for Matrix Synapse server.
            
            ## Installation
            
            ```bash
            wget https://github.com/EPTLLC/EPT-MX-ADM/releases/download/${{ github.ref_name }}/ept-mx-adm-${{ github.ref_name }}.tar.gz
            tar -xzf ept-mx-adm-${{ github.ref_name }}.tar.gz
            cd EPT-MX-ADM
            pip install -r requirements.txt
            python app.py
            ```
          files: dist/*
          draft: false
          prerelease: false  # и его проверь
